# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4TopfG0ACLQDjddepFwTV2iCcPxeC6I
"""

a = float(input("Enter first number: "))
b = float(input("Enter second number: "))

op = input("Enter operation (+, -, *, /): ")

if op == "+":
    print("Result:", a + b)

elif op == "-":
    print("Result:", a - b)

elif op == "*":
    print("Result:", a * b)

elif op == "/":
    print("Result:", a / b)

else:
    print("Invalid operation")